// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlK3Pm3X5e9Nw31V8SPfm8o1CvPlisoEU',
    appId: '1:838061114925:web:4489f878453573b9229aa4',
    messagingSenderId: '838061114925',
    projectId: 'modulo-squares-staging',
    authDomain: 'modulo-squares-staging.firebaseapp.com',
    storageBucket: 'modulo-squares-staging.firebasestorage.app',
    measurementId: 'G-EJDZWN4Z3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYm0u62vZdasCiKcKtW_LOFD9qu-z4Ys',
    appId: '1:838061114925:android:9a9206d7065e2e3e229aa4',
    messagingSenderId: '838061114925',
    projectId: 'modulo-squares-staging',
    storageBucket: 'modulo-squares-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANg0NnZRQKbco2MOOx4-dNyCOSKdh6Ti0',
    appId: '1:838061114925:ios:f607167ffa35e7bb229aa4',
    messagingSenderId: '838061114925',
    projectId: 'modulo-squares-staging',
    storageBucket: 'modulo-squares-staging.firebasestorage.app',
    iosClientId: '838061114925-ms9cle62f1qlq182movucpdl7ttqk7e4.apps.googleusercontent.com',
    iosBundleId: 'com.nelsongrey.modulosquares.app.ios',
  );

}