// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpeiIDzxlnIagNvjJb4Yk1oOpvuwLga-c',
    appId: '1:239807122511:web:89c06cdf09b0845900ee3a',
    messagingSenderId: '239807122511',
    projectId: 'modulo-84c4d',
    authDomain: 'modulo-84c4d.firebaseapp.com',
    storageBucket: 'modulo-84c4d.firebasestorage.app',
    measurementId: 'G-KPX3GHW9VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfi_TIlO7-BoxhcO3dQUAxmflxAiAj6Y',
    appId: '1:239807122511:android:b0a89e46830e6d6400ee3a',
    messagingSenderId: '239807122511',
    projectId: 'modulo-84c4d',
    storageBucket: 'modulo-84c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1dThz9ccZas_dgZi1DOHuCSxXDBnG1g',
    appId: '1:239807122511:ios:47e91bc22b2729bc00ee3a',
    messagingSenderId: '239807122511',
    projectId: 'modulo-84c4d',
    storageBucket: 'modulo-84c4d.firebasestorage.app',
    iosBundleId: 'com.example.modulo',
  );
}
